// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAYchriv9EzWIKYofAQKu8T4X26jSV-5A',
    appId: '1:760989910539:web:bb35ece55e3c49b4eea90e',
    messagingSenderId: '760989910539',
    projectId: 'job-finder-app-4f13d',
    authDomain: 'job-finder-app-4f13d.firebaseapp.com',
    storageBucket: 'job-finder-app-4f13d.firebasestorage.app',
    measurementId: 'G-47H42N0KJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX1heDuQcT0dKPlopa7fErvymt_fY9mJI',
    appId: '1:760989910539:android:eac63ca6d930007beea90e',
    messagingSenderId: '760989910539',
    projectId: 'job-finder-app-4f13d',
    storageBucket: 'job-finder-app-4f13d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqv6Q9_yP2r-uV7-go8rPvC9RnQOjiZ0',
    appId: '1:760989910539:ios:438b4f9a826a570beea90e',
    messagingSenderId: '760989910539',
    projectId: 'job-finder-app-4f13d',
    storageBucket: 'job-finder-app-4f13d.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBqv6Q9_yP2r-uV7-go8rPvC9RnQOjiZ0',
    appId: '1:760989910539:ios:438b4f9a826a570beea90e',
    messagingSenderId: '760989910539',
    projectId: 'job-finder-app-4f13d',
    storageBucket: 'job-finder-app-4f13d.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAYchriv9EzWIKYofAQKu8T4X26jSV-5A',
    appId: '1:760989910539:web:6ede45d5ffef639ceea90e',
    messagingSenderId: '760989910539',
    projectId: 'job-finder-app-4f13d',
    authDomain: 'job-finder-app-4f13d.firebaseapp.com',
    storageBucket: 'job-finder-app-4f13d.firebasestorage.app',
    measurementId: 'G-2K685RMFY1',
  );
}
